//! Literal fixtures transcribed from opacity-fixtures/literal-fixtures.json.
//! Expectations were authored before candidate execution, not painted from it.
use crate::reuse_fixtures::Fixture;
use eris_raster_core::{
    Command, Frame, Profile, Rect, Result, SourceImage, SourceMask, plan_with_masks_for_profile,
};

/// The first three frames have identical buffer sizes but change group origin,
/// shape, opacity, primitive inputs and row tables. The fourth changes scratch
/// size only. These literal RGB arrays are not generated by the candidate.
pub fn reuse_fixtures() -> Result<Vec<Fixture>> {
    let descriptions = [
        (
            "opacity-reuse-a",
            Rect::new(0.0, 0.0, 4.0, 1.0),
            0.5,
            [65, 0, 0, 255],
            Rect::new(1.0, 0.0, 1.0, 1.0),
            [0, 65, 0, 255],
            2,
            0,
            [0, 0, 65, 255],
            [0x210000, 0x002100, 0x000021, 0x210000, 0, 0, 0, 0],
        ),
        (
            "opacity-reuse-b",
            Rect::new(0.0, 1.0, 4.0, 1.0),
            0.25,
            [0, 0, 65, 255],
            Rect::new(3.0, 1.0, 1.0, 1.0),
            [0, 65, 0, 255],
            2,
            1,
            [65, 0, 0, 255],
            [0, 0, 0, 0, 0x000010, 0x000010, 0x100000, 0x001000],
        ),
        (
            "opacity-reuse-c",
            Rect::new(1.0, 0.0, 2.0, 2.0),
            0.75,
            [65, 65, 65, 255],
            Rect::new(1.0, 1.0, 1.0, 1.0),
            [0, 0, 0, 255],
            2,
            0,
            [65, 0, 0, 255],
            [0, 0x313131, 0x310000, 0, 0, 0, 0x313131, 0],
        ),
        (
            "opacity-reuse-resized",
            Rect::new(0.0, 0.0, 3.0, 2.0),
            0.5,
            [65, 65, 65, 255],
            Rect::new(0.0, 1.0, 1.0, 1.0),
            [0, 0, 0, 255],
            2,
            0,
            [65, 0, 0, 255],
            [0x212121, 0x212121, 0x210000, 0, 0, 0x212121, 0x212121, 0],
        ),
    ];
    let mut cases = Vec::new();
    for (name, backing, opacity, color, image_rect, image, row, y, glyph, expected) in descriptions
    {
        let commands = [
            Command::PushOpacity(opacity),
            Command::Rect {
                rect: backing,
                rgba: color,
                radius: 0.0,
            },
            Command::Image {
                rect: image_rect,
                source: 0,
            },
            Command::Glyph {
                source: 0,
                rows: 0,
                y,
                rgba: glyph,
            },
            Command::PopOpacity,
        ];
        let plan = plan_with_masks_for_profile(
            Profile::Native,
            Frame::new(4, 2, 0),
            &commands,
            &[SourceImage {
                width: 1,
                height: 1,
                rgba: &image,
            }],
            &[SourceMask {
                width: 1,
                height: 1,
                coverage: &[255],
            }],
            &[&[row]],
        )?;
        let expected_scratch = if name == "opacity-reuse-resized" {
            48
        } else {
            32
        };
        if plan.group_scratch_bytes() != expected_scratch {
            return Err("opacity reuse scratch extent mismatch".into());
        }
        cases.push(Fixture {
            name,
            plan,
            expected: expected.to_vec(),
        });
    }
    Ok(cases)
}

pub fn fixtures() -> Result<Vec<Fixture>> {
    let mut cases = Vec::new();
    {
        let frame = Frame {
            width: 3,
            height: 1,
            clear: 0x000000,
            caller_clip: Rect::new(0.0, 0.0, 3.0, 1.0),
            document_offset: (0.0, 0.0),
            viewport_offset: (0.0, 0.0),
        };
        let commands = [
            Command::PushOpacity(0.5),
            Command::Rect {
                rect: Rect::new(0.0, 0.0, 1.0, 1.0),
                rgba: [65, 0, 0, 255],
                radius: 0.0,
            },
            Command::PopOpacity,
        ];
        let images = [];
        let masks = [];
        let rows: &[&[i32]] = &[];
        let plan =
            plan_with_masks_for_profile(Profile::Native, frame, &commands, &images, &masks, rows);
        let plan = plan?;
        if plan.group_scratch_bytes() == 0 {
            return Err("literal group lost its native scratch route".into());
        }
        cases.push(Fixture {
            name: "halfway-red-65-over-black",
            plan,
            expected: vec![0x210000, 0x000000, 0x000000],
        });
    }
    {
        let frame = Frame {
            width: 8,
            height: 2,
            clear: 0xffffff,
            caller_clip: Rect::new(0.0, 0.0, 8.0, 2.0),
            document_offset: (0.0, 0.0),
            viewport_offset: (0.0, 0.0),
        };
        let commands = [
            Command::PushOpacity(0.5),
            Command::Rect {
                rect: Rect::new(0.0, 0.0, 6.0, 2.0),
                rgba: [255, 0, 0, 255],
                radius: 0.0,
            },
            Command::Rect {
                rect: Rect::new(2.0, 0.0, 4.0, 2.0),
                rgba: [0, 0, 255, 255],
                radius: 0.0,
            },
            Command::PopOpacity,
            Command::Rect {
                rect: Rect::new(7.0, 0.0, 1.0, 2.0),
                rgba: [0, 255, 0, 255],
                radius: 0.0,
            },
        ];
        let images = [];
        let masks = [];
        let rows: &[&[i32]] = &[];
        let plan =
            plan_with_masks_for_profile(Profile::Native, frame, &commands, &images, &masks, rows);
        let plan = plan?;
        if plan.group_scratch_bytes() == 0 {
            return Err("literal group lost its native scratch route".into());
        }
        cases.push(Fixture {
            name: "opaque-backed-overlap-and-after-pop",
            plan,
            expected: vec![
                0xff8080, 0xff8080, 0x8080ff, 0x8080ff, 0x8080ff, 0x8080ff, 0xffffff, 0x00ff00,
                0xff8080, 0xff8080, 0x8080ff, 0x8080ff, 0x8080ff, 0x8080ff, 0xffffff, 0x00ff00,
            ],
        });
    }
    {
        let frame = Frame {
            width: 4,
            height: 1,
            clear: 0xffffff,
            caller_clip: Rect::new(0.0, 0.0, 4.0, 1.0),
            document_offset: (0.0, 0.0),
            viewport_offset: (0.0, 0.0),
        };
        let commands = [
            Command::PushOpacity(0.5),
            Command::Rect {
                rect: Rect::new(0.0, 0.0, 3.0, 1.0),
                rgba: [255, 0, 0, 255],
                radius: 0.0,
            },
            Command::PushOpacity(0.5),
            Command::Rect {
                rect: Rect::new(1.0, 0.0, 1.0, 1.0),
                rgba: [0, 0, 255, 255],
                radius: 0.0,
            },
            Command::PopOpacity,
            Command::PopOpacity,
        ];
        let images = [];
        let masks = [];
        let rows: &[&[i32]] = &[];
        let plan =
            plan_with_masks_for_profile(Profile::Native, frame, &commands, &images, &masks, rows);
        let plan = plan?;
        if plan.group_scratch_bytes() == 0 {
            return Err("literal group lost its native scratch route".into());
        }
        cases.push(Fixture {
            name: "nested-opaque-blue-over-red",
            plan,
            expected: vec![0xff8080, 0xbf80bf, 0xff8080, 0xffffff],
        });
    }
    {
        let frame = Frame {
            width: 3,
            height: 1,
            clear: 0x000000,
            caller_clip: Rect::new(0.0, 0.0, 3.0, 1.0),
            document_offset: (0.0, 0.0),
            viewport_offset: (0.0, 0.0),
        };
        let commands = [
            Command::PushOpacity(0.25),
            Command::Rect {
                rect: Rect::new(0.0, 0.0, 2.0, 1.0),
                rgba: [255, 255, 255, 255],
                radius: 0.0,
            },
            Command::Image {
                rect: Rect::new(1.0, 0.0, 1.0, 1.0),
                source: 0,
            },
            Command::PopOpacity,
        ];
        let images = [SourceImage {
            width: 1,
            height: 1,
            rgba: &[255, 0, 0, 128],
        }];
        let masks = [];
        let rows: &[&[i32]] = &[];
        let plan =
            plan_with_masks_for_profile(Profile::Native, frame, &commands, &images, &masks, rows);
        let plan = plan?;
        if plan.group_scratch_bytes() == 0 {
            return Err("literal group lost its native scratch route".into());
        }
        cases.push(Fixture {
            name: "quarter-group-with-translucent-image-on-white",
            plan,
            expected: vec![0x404040, 0x402020, 0x000000],
        });
    }
    {
        let frame = Frame {
            width: 3,
            height: 1,
            clear: 0x000000,
            caller_clip: Rect::new(0.0, 0.0, 3.0, 1.0),
            document_offset: (0.0, 0.0),
            viewport_offset: (0.0, 0.0),
        };
        let commands = [
            Command::PushOpacity(0.5),
            Command::Rect {
                rect: Rect::new(0.0, 0.0, 2.0, 1.0),
                rgba: [255, 255, 255, 255],
                radius: 0.0,
            },
            Command::Glyph {
                source: 0,
                rows: 0,
                y: 0,
                rgba: [255, 0, 0, 128],
            },
            Command::PopOpacity,
        ];
        let images = [];
        let masks = [SourceMask {
            width: 2,
            height: 1,
            coverage: &[0, 128],
        }];
        let rows: &[&[i32]] = &[&[0]];
        let plan =
            plan_with_masks_for_profile(Profile::Native, frame, &commands, &images, &masks, rows);
        let plan = plan?;
        if plan.group_scratch_bytes() == 0 {
            return Err("literal group lost its native scratch route".into());
        }
        cases.push(Fixture {
            name: "coverage-times-alpha-truncates-before-group-pop",
            plan,
            expected: vec![0x808080, 0x806060, 0x000000],
        });
    }
    {
        let frame = Frame {
            width: 6,
            height: 2,
            clear: 0xffffff,
            caller_clip: Rect::new(0.0, 0.0, 6.0, 2.0),
            document_offset: (0.0, -5.0),
            viewport_offset: (0.0, 0.0),
        };
        let commands = [
            Command::PushOpacity(0.5),
            Command::Rect {
                rect: Rect::new(0.0, 5.0, 5.0, 2.0),
                rgba: [255, 0, 0, 255],
                radius: 0.0,
            },
            Command::PushClip(Rect::new(0.0, 5.0, 1.0, 1.0)),
            Command::PushFixed,
            Command::Rect {
                rect: Rect::new(3.0, 0.0, 1.0, 1.0),
                rgba: [0, 0, 255, 255],
                radius: 0.0,
            },
            Command::PopFixed,
            Command::Rect {
                rect: Rect::new(0.0, 5.0, 1.0, 1.0),
                rgba: [0, 255, 0, 255],
                radius: 0.0,
            },
            Command::PopClip,
            Command::PopOpacity,
        ];
        let images = [];
        let masks = [];
        let rows: &[&[i32]] = &[];
        let plan =
            plan_with_masks_for_profile(Profile::Native, frame, &commands, &images, &masks, rows);
        let plan = plan?;
        if plan.group_scratch_bytes() == 0 {
            return Err("literal group lost its native scratch route".into());
        }
        cases.push(Fixture {
            name: "fixed-escape-stays-inside-opaque-backing",
            plan,
            expected: vec![
                0x80ff80, 0xff8080, 0xff8080, 0x8080ff, 0xff8080, 0xffffff, 0xff8080, 0xff8080,
                0xff8080, 0xff8080, 0xff8080, 0xffffff,
            ],
        });
    }
    {
        let frame = Frame {
            width: 1,
            height: 1,
            clear: 0x000000,
            caller_clip: Rect::new(0.0, 0.0, 1.0, 1.0),
            document_offset: (0.0, 0.0),
            viewport_offset: (0.0, 0.0),
        };
        let commands = [
            Command::PushOpacity(1.0),
            Command::Rect {
                rect: Rect::new(0.0, 0.0, 1.0, 1.0),
                rgba: [1, 0, 0, 128],
                radius: 0.0,
            },
            Command::Rect {
                rect: Rect::new(0.0, 0.0, 1.0, 1.0),
                rgba: [0, 0, 0, 1],
                radius: 0.0,
            },
            Command::PopOpacity,
        ];
        let images = [];
        let masks = [];
        let rows: &[&[i32]] = &[];
        let plan =
            plan_with_masks_for_profile(Profile::Native, frame, &commands, &images, &masks, rows);
        let plan = plan?;
        if plan.group_scratch_bytes() != 0 {
            return Err("zero/unit scope unexpectedly allocated a layer".into());
        }
        cases.push(Fixture {
            name: "unit-scope-preserves-current-direct-rgb8-target",
            plan,
            expected: vec![0x010000],
        });
    }
    {
        let frame = Frame {
            width: 3,
            height: 1,
            clear: 0xffffff,
            caller_clip: Rect::new(0.5, 0.0, 1.0, 1.0),
            document_offset: (0.0, 0.0),
            viewport_offset: (0.0, 0.0),
        };
        let commands = [
            Command::PushOpacity(0.5),
            Command::Rect {
                rect: Rect::new(0.0, 0.0, 3.0, 1.0),
                rgba: [255, 0, 0, 255],
                radius: 0.0,
            },
            Command::PopOpacity,
        ];
        let images = [];
        let masks = [];
        let rows: &[&[i32]] = &[];
        let plan =
            plan_with_masks_for_profile(Profile::Native, frame, &commands, &images, &masks, rows);
        let plan = plan?;
        if plan.group_scratch_bytes() == 0 {
            return Err("literal group lost its native scratch route".into());
        }
        cases.push(Fixture {
            name: "fractional-caller-clip-integer-origin-containment",
            plan,
            expected: vec![0xffffff, 0xff8080, 0xffffff],
        });
    }
    {
        let frame = Frame {
            width: 4,
            height: 1,
            clear: 0xffffff,
            caller_clip: Rect::new(0.0, 0.0, 4.0, 1.0),
            document_offset: (0.0, 0.0),
            viewport_offset: (0.0, 0.0),
        };
        let commands = [
            Command::PushOpacity(0.5),
            Command::Rect {
                rect: Rect::new(0.0, 0.0, 2.0, 1.0),
                rgba: [255, 0, 0, 255],
                radius: 0.0,
            },
            Command::Rect {
                rect: Rect::new(1.0, 0.0, 2.0, 1.0),
                rgba: [0, 0, 255, 255],
                radius: 0.0,
            },
            Command::PopOpacity,
        ];
        let images = [];
        let masks = [];
        let rows: &[&[i32]] = &[];
        let plan =
            plan_with_masks_for_profile(Profile::Native, frame, &commands, &images, &masks, rows);
        if plan.as_ref().err().map(String::as_str)
            != Some("opacity group requires opaque rectangular backing")
        {
            return Err(
                "uncertified-multiple-rect-backing-remains-fallback: refusal mismatch".into(),
            );
        }
    }
    {
        let frame = Frame {
            width: 2,
            height: 1,
            clear: 0xffffff,
            caller_clip: Rect::new(0.0, 0.0, 2.0, 1.0),
            document_offset: (0.0, 0.0),
            viewport_offset: (0.0, 0.0),
        };
        let commands = [
            Command::PushOpacity(0.5),
            Command::Image {
                rect: Rect::new(0.0, 0.0, 1.0, 1.0),
                source: 0,
            },
            Command::PopOpacity,
        ];
        let images = [SourceImage {
            width: 1,
            height: 1,
            rgba: &[255, 0, 0, 128],
        }];
        let masks = [];
        let rows: &[&[i32]] = &[];
        let plan =
            plan_with_masks_for_profile(Profile::Native, frame, &commands, &images, &masks, rows);
        if plan.as_ref().err().map(String::as_str)
            != Some("opacity group requires opaque rectangular backing")
        {
            return Err("translucent-image-only-group-remains-fallback: refusal mismatch".into());
        }
    }
    {
        let frame = Frame {
            width: 2,
            height: 1,
            clear: 0xffffff,
            caller_clip: Rect::new(0.0, 0.0, 2.0, 1.0),
            document_offset: (0.0, 0.0),
            viewport_offset: (0.0, 0.0),
        };
        let commands = [
            Command::PushOpacity(0.0),
            Command::Rect {
                rect: Rect::new(0.0, 0.0, 2.0, 1.0),
                rgba: [255, 0, 0, 128],
                radius: 0.0,
            },
            Command::PopOpacity,
            Command::Rect {
                rect: Rect::new(1.0, 0.0, 1.0, 1.0),
                rgba: [0, 255, 0, 255],
                radius: 0.0,
            },
        ];
        let images = [];
        let masks = [];
        let rows: &[&[i32]] = &[];
        let plan =
            plan_with_masks_for_profile(Profile::Native, frame, &commands, &images, &masks, rows);
        let plan = plan?;
        if plan.group_scratch_bytes() != 0 {
            return Err("zero/unit scope unexpectedly allocated a layer".into());
        }
        cases.push(Fixture {
            name: "zero-scope-suppresses-pixels-and-restores-root",
            plan,
            expected: vec![0xffffff, 0x00ff00],
        });
    }
    {
        let frame = Frame {
            width: 1,
            height: 1,
            clear: 0x000000,
            caller_clip: Rect::new(0.0, 0.0, 1.0, 1.0),
            document_offset: (0.0, 0.0),
            viewport_offset: (0.0, 0.0),
        };
        let commands = [
            Command::PushOpacity(0.1),
            Command::Rect {
                rect: Rect::new(0.0, 0.0, 1.0, 1.0),
                rgba: [255, 0, 0, 255],
                radius: 0.0,
            },
            Command::PopOpacity,
        ];
        let images = [];
        let masks = [];
        let rows: &[&[i32]] = &[];
        let plan =
            plan_with_masks_for_profile(Profile::Native, frame, &commands, &images, &masks, rows);
        if plan.as_ref().err().map(String::as_str) != Some("unsupported opacity value") {
            return Err(
                "non-grid-opacity-remains-fallback-with-original-pixels: refusal mismatch".into(),
            );
        }
    }
    Ok(cases)
}
