[package]
name = "eris-vulkan-raster-prototype"
version = "0.0.0"
edition = "2024"
rust-version = "1.88"
publish = false
license = "MIT"

[workspace]

[dependencies]
wgpu = { version = "=30.0.1", default-features = false, features = ["std", "vulkan", "wgsl"] }

[profile.dev]
debug = 0

[lints.rust]
unsafe_code = "forbid"
