// Source-only worker-text assumptions. No pixel golden or planner calls.
use eris_vulkan_raster_prototype::{Frame, Rect};
pub struct ExpectedText {
    pub text: &'static str,
    pub bold: bool,
    pub italic: bool,
    pub monospace: bool,
    pub fixed: bool,
    pub clipped: bool,
    pub size: f32,
    pub rgba: [u8; 4],
}
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum DrawingKind {
    Rect,
    Text,
    Image,
    Line,
}
pub struct ExpectedImage {
    pub key: &'static str,
    pub width: u32,
    pub height: u32,
    pub rgba: &'static [u8],
    pub references: usize,
}
pub struct WorkerTextFixture {
    pub name: &'static str,
    pub html_file: &'static str,
    pub frame: Frame,
    pub texts: &'static [ExpectedText],
    pub drawing_order: &'static [DrawingKind],
    pub images: &'static [ExpectedImage],
    pub expected_fallback: Option<&'static str>,
}
pub fn fixtures() -> Vec<WorkerTextFixture> {
    vec![
        WorkerTextFixture {
            name: "worker-text-flow-unicode",
            html_file: "html/worker-text-flow-unicode.html",
            frame: Frame {
                width: 160,
                height: 80,
                clear: 0xffffff,
                caller_clip: Rect::new(
                    f32::from_bits(0x00000000),
                    f32::from_bits(0x00000000),
                    f32::from_bits(0x43200000),
                    f32::from_bits(0x42a00000),
                ),
                document_offset: (f32::from_bits(0x00000000), f32::from_bits(0x00000000)),
                viewport_offset: (f32::from_bits(0x00000000), f32::from_bits(0x00000000)),
            },
            texts: &[
                ExpectedText {
                    text: "AV",
                    bold: false,
                    italic: false,
                    monospace: false,
                    fixed: false,
                    clipped: false,
                    size: f32::from_bits(0x41800000),
                    rgba: [16, 32, 48, 255],
                },
                ExpectedText {
                    text: " ",
                    bold: false,
                    italic: false,
                    monospace: false,
                    fixed: false,
                    clipped: false,
                    size: f32::from_bits(0x41800000),
                    rgba: [16, 32, 48, 255],
                },
                ExpectedText {
                    text: "To",
                    bold: false,
                    italic: false,
                    monospace: false,
                    fixed: false,
                    clipped: false,
                    size: f32::from_bits(0x41800000),
                    rgba: [16, 32, 48, 255],
                },
                ExpectedText {
                    text: "\u{e9}",
                    bold: false,
                    italic: false,
                    monospace: false,
                    fixed: false,
                    clipped: false,
                    size: f32::from_bits(0x41800000),
                    rgba: [16, 32, 48, 255],
                },
                ExpectedText {
                    text: " ",
                    bold: false,
                    italic: false,
                    monospace: false,
                    fixed: false,
                    clipped: false,
                    size: f32::from_bits(0x41800000),
                    rgba: [16, 32, 48, 255],
                },
                ExpectedText {
                    text: "\u{3a9}",
                    bold: false,
                    italic: false,
                    monospace: false,
                    fixed: false,
                    clipped: false,
                    size: f32::from_bits(0x41800000),
                    rgba: [16, 32, 48, 255],
                },
            ],
            drawing_order: &[
                DrawingKind::Rect,
                DrawingKind::Text,
                DrawingKind::Text,
                DrawingKind::Text,
                DrawingKind::Text,
                DrawingKind::Text,
                DrawingKind::Text,
            ],
            images: &[],
            expected_fallback: None,
        },
        WorkerTextFixture {
            name: "worker-text-font-flags",
            html_file: "html/worker-text-font-flags.html",
            frame: Frame {
                width: 160,
                height: 80,
                clear: 0xffffff,
                caller_clip: Rect::new(
                    f32::from_bits(0x00000000),
                    f32::from_bits(0x00000000),
                    f32::from_bits(0x43200000),
                    f32::from_bits(0x42a00000),
                ),
                document_offset: (f32::from_bits(0x00000000), f32::from_bits(0x00000000)),
                viewport_offset: (f32::from_bits(0x00000000), f32::from_bits(0x00000000)),
            },
            texts: &[
                ExpectedText {
                    text: "AV",
                    bold: false,
                    italic: false,
                    monospace: false,
                    fixed: false,
                    clipped: false,
                    size: f32::from_bits(0x41800000),
                    rgba: [16, 32, 48, 255],
                },
                ExpectedText {
                    text: "To",
                    bold: true,
                    italic: false,
                    monospace: false,
                    fixed: false,
                    clipped: false,
                    size: f32::from_bits(0x41800000),
                    rgba: [160, 32, 48, 255],
                },
                ExpectedText {
                    text: "jTy",
                    bold: false,
                    italic: true,
                    monospace: false,
                    fixed: false,
                    clipped: false,
                    size: f32::from_bits(0x41800000),
                    rgba: [120, 20, 200, 128],
                },
                ExpectedText {
                    text: "MM",
                    bold: true,
                    italic: false,
                    monospace: true,
                    fixed: false,
                    clipped: false,
                    size: f32::from_bits(0x41800000),
                    rgba: [0, 128, 64, 255],
                },
            ],
            drawing_order: &[
                DrawingKind::Rect,
                DrawingKind::Text,
                DrawingKind::Text,
                DrawingKind::Text,
                DrawingKind::Text,
            ],
            images: &[],
            expected_fallback: None,
        },
        WorkerTextFixture {
            name: "worker-text-overflow-restoration",
            html_file: "html/worker-text-overflow-restoration.html",
            frame: Frame {
                width: 160,
                height: 80,
                clear: 0xffffff,
                caller_clip: Rect::new(
                    f32::from_bits(0x00000000),
                    f32::from_bits(0x00000000),
                    f32::from_bits(0x43200000),
                    f32::from_bits(0x42a00000),
                ),
                document_offset: (f32::from_bits(0x00000000), f32::from_bits(0x00000000)),
                viewport_offset: (f32::from_bits(0x00000000), f32::from_bits(0x00000000)),
            },
            texts: &[
                ExpectedText {
                    text: "AVAVAV",
                    bold: false,
                    italic: false,
                    monospace: false,
                    fixed: false,
                    clipped: true,
                    size: f32::from_bits(0x41a00000),
                    rgba: [16, 32, 48, 255],
                },
                ExpectedText {
                    text: "AFTER",
                    bold: false,
                    italic: false,
                    monospace: false,
                    fixed: false,
                    clipped: false,
                    size: f32::from_bits(0x41800000),
                    rgba: [16, 32, 48, 255],
                },
            ],
            drawing_order: &[DrawingKind::Rect, DrawingKind::Text, DrawingKind::Text],
            images: &[],
            expected_fallback: None,
        },
        WorkerTextFixture {
            name: "worker-text-scroll-fixed",
            html_file: "html/worker-text-scroll-fixed.html",
            frame: Frame {
                width: 160,
                height: 80,
                clear: 0xffffff,
                caller_clip: Rect::new(
                    f32::from_bits(0x00000000),
                    f32::from_bits(0x00000000),
                    f32::from_bits(0x43200000),
                    f32::from_bits(0x42a00000),
                ),
                document_offset: (f32::from_bits(0x00000000), f32::from_bits(0xc1c00000)),
                viewport_offset: (f32::from_bits(0x00000000), f32::from_bits(0x00000000)),
            },
            texts: &[
                ExpectedText {
                    text: "SCROLL",
                    bold: false,
                    italic: false,
                    monospace: false,
                    fixed: false,
                    clipped: true,
                    size: f32::from_bits(0x41800000),
                    rgba: [16, 32, 48, 255],
                },
                ExpectedText {
                    text: "FIXED",
                    bold: false,
                    italic: false,
                    monospace: false,
                    fixed: true,
                    clipped: false,
                    size: f32::from_bits(0x41800000),
                    rgba: [0, 0, 255, 255],
                },
                ExpectedText {
                    text: "AFTER",
                    bold: false,
                    italic: false,
                    monospace: false,
                    fixed: false,
                    clipped: false,
                    size: f32::from_bits(0x41800000),
                    rgba: [0, 128, 0, 255],
                },
            ],
            drawing_order: &[
                DrawingKind::Rect,
                DrawingKind::Text,
                DrawingKind::Text,
                DrawingKind::Text,
            ],
            images: &[],
            expected_fallback: None,
        },
        WorkerTextFixture {
            name: "worker-text-image-order",
            html_file: "html/worker-text-image-order.html",
            frame: Frame {
                width: 160,
                height: 80,
                clear: 0xffffff,
                caller_clip: Rect::new(
                    f32::from_bits(0x00000000),
                    f32::from_bits(0x00000000),
                    f32::from_bits(0x43200000),
                    f32::from_bits(0x42a00000),
                ),
                document_offset: (f32::from_bits(0x00000000), f32::from_bits(0x00000000)),
                viewport_offset: (f32::from_bits(0x00000000), f32::from_bits(0x00000000)),
            },
            texts: &[
                ExpectedText {
                    text: "AV",
                    bold: false,
                    italic: false,
                    monospace: false,
                    fixed: false,
                    clipped: false,
                    size: f32::from_bits(0x41a00000),
                    rgba: [0, 128, 0, 255],
                },
                ExpectedText {
                    text: "To",
                    bold: false,
                    italic: false,
                    monospace: false,
                    fixed: false,
                    clipped: false,
                    size: f32::from_bits(0x41a00000),
                    rgba: [128, 0, 0, 128],
                },
            ],
            drawing_order: &[
                DrawingKind::Rect,
                DrawingKind::Text,
                DrawingKind::Image,
                DrawingKind::Text,
                DrawingKind::Image,
            ],
            images: &[ExpectedImage {
                key: "two-pixels.png",
                width: 2,
                height: 1,
                rgba: &[255, 0, 0, 255, 0, 0, 255, 128],
                references: 2,
            }],
            expected_fallback: None,
        },
        WorkerTextFixture {
            name: "worker-text-alpha-underline",
            html_file: "html/worker-text-alpha-underline.html",
            frame: Frame {
                width: 160,
                height: 80,
                clear: 0xffffff,
                caller_clip: Rect::new(
                    f32::from_bits(0x00000000),
                    f32::from_bits(0x00000000),
                    f32::from_bits(0x43200000),
                    f32::from_bits(0x42a00000),
                ),
                document_offset: (f32::from_bits(0x00000000), f32::from_bits(0x00000000)),
                viewport_offset: (f32::from_bits(0x00000000), f32::from_bits(0x00000000)),
            },
            texts: &[
                ExpectedText {
                    text: "AA",
                    bold: false,
                    italic: false,
                    monospace: true,
                    fixed: false,
                    clipped: false,
                    size: f32::from_bits(0x41800000),
                    rgba: [0, 0, 128, 128],
                },
                ExpectedText {
                    text: "AA",
                    bold: false,
                    italic: false,
                    monospace: true,
                    fixed: false,
                    clipped: false,
                    size: f32::from_bits(0x41800000),
                    rgba: [128, 0, 0, 128],
                },
            ],
            drawing_order: &[
                DrawingKind::Rect,
                DrawingKind::Text,
                DrawingKind::Line,
                DrawingKind::Text,
                DrawingKind::Line,
            ],
            images: &[],
            expected_fallback: None,
        },
        WorkerTextFixture {
            name: "worker-text-rounded-fallback",
            html_file: "html/worker-text-rounded-fallback.html",
            frame: Frame {
                width: 160,
                height: 80,
                clear: 0xffffff,
                caller_clip: Rect::new(
                    f32::from_bits(0x00000000),
                    f32::from_bits(0x00000000),
                    f32::from_bits(0x43200000),
                    f32::from_bits(0x42a00000),
                ),
                document_offset: (f32::from_bits(0x00000000), f32::from_bits(0x00000000)),
                viewport_offset: (f32::from_bits(0x00000000), f32::from_bits(0x00000000)),
            },
            texts: &[
                ExpectedText {
                    text: "ROUND",
                    bold: false,
                    italic: false,
                    monospace: false,
                    fixed: false,
                    clipped: false,
                    size: f32::from_bits(0x41800000),
                    rgba: [64, 0, 0, 255],
                },
                ExpectedText {
                    text: "AFTER",
                    bold: false,
                    italic: false,
                    monospace: false,
                    fixed: false,
                    clipped: false,
                    size: f32::from_bits(0x41800000),
                    rgba: [0, 0, 128, 255],
                },
            ],
            drawing_order: &[
                DrawingKind::Rect,
                DrawingKind::Rect,
                DrawingKind::Text,
                DrawingKind::Text,
            ],
            images: &[],
            expected_fallback: Some("unsupported-rounded-rectangle"),
        },
    ]
}
