// @generated by tools/generate_js_identifiers.py; do not edit.
// Unicode 18.0.0 ID_Start and ID_Continue; no normalization or XID approximation.
// Source: https://www.unicode.org/Public/18.0.0/ucd/DerivedCoreProperties.txt
// Source SHA-256: 09c928886a178fcafd93c29e4bd59073a058e5a100b716d425cb563ab50f68c9
// Provenance: tests/upstream/unicode/18.0.0/manifest.json
// License copied verbatim as line comments below:
//
// UNICODE LICENSE V3
//
// COPYRIGHT AND PERMISSION NOTICE
//
// Copyright © 1991-2026 Unicode, Inc.
//
// NOTICE TO USER: Carefully read the following legal agreement. BY
// DOWNLOADING, INSTALLING, COPYING OR OTHERWISE USING DATA FILES, AND/OR
// SOFTWARE, YOU UNEQUIVOCALLY ACCEPT, AND AGREE TO BE BOUND BY, ALL OF THE
// TERMS AND CONDITIONS OF THIS AGREEMENT. IF YOU DO NOT AGREE, DO NOT
// DOWNLOAD, INSTALL, COPY, DISTRIBUTE OR USE THE DATA FILES OR SOFTWARE.
//
// Permission is hereby granted, free of charge, to any person obtaining a
// copy of data files and any associated documentation (the "Data Files") or
// software and any associated documentation (the "Software") to deal in the
// Data Files or Software without restriction, including without limitation
// the rights to use, copy, modify, merge, publish, distribute, and/or sell
// copies of the Data Files or Software, and to permit persons to whom the
// Data Files or Software are furnished to do so, provided that either (a)
// this copyright and permission notice appear with all copies of the Data
// Files or Software, or (b) this copyright and permission notice appear in
// associated Documentation.
//
// THE DATA FILES AND SOFTWARE ARE PROVIDED "AS IS", WITHOUT WARRANTY OF ANY
// KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
// MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT OF
// THIRD PARTY RIGHTS.
//
// IN NO EVENT SHALL THE COPYRIGHT HOLDER OR HOLDERS INCLUDED IN THIS NOTICE
// BE LIABLE FOR ANY CLAIM, OR ANY SPECIAL INDIRECT OR CONSEQUENTIAL DAMAGES,
// OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS,
// WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION,
// ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THE DATA
// FILES OR SOFTWARE.
//
// Except as contained in this notice, the name of a copyright holder shall
// not be used in advertising or otherwise to promote the sale, use or other
// dealings in these Data Files or Software without prior written
// authorization of the copyright holder.

// One bounded page-index read and one bounded bitmap-word read per lookup.
// ASCII takes its separate fast path. The parser charges this real lookup bound.
pub(crate) const IDENTIFIER_LOOKUP_WORK: usize = 2;

#[inline]
pub(crate) fn is_identifier_start(value: char) -> bool {
    if value.is_ascii() {
        return matches!(value, '$' | '_' | 'a'..='z' | 'A'..='Z');
    }
    membership(value, 0)
}

#[inline]
pub(crate) fn is_identifier_part(value: char) -> bool {
    if value.is_ascii() {
        return matches!(value, '$' | '_' | 'a'..='z' | 'A'..='Z' | '0'..='9');
    }
    matches!(value, '\u{200c}' | '\u{200d}') || membership(value, 1)
}

// Fixed scalar-domain index; page IDs and eight-word pages are generator-checked.
// Bits alternate ID_Start / ID_Continue. No loops, allocation or normalization.
#[inline]
fn membership(value: char, property: u32) -> bool {
    let scalar = value as u32;
    let page = PAGE_INDEX[(scalar >> 8) as usize] as usize;
    let bit = ((scalar & 0xff) << 1) | property;
    (IDENTIFIER_PAGES[page][(bit >> 6) as usize] >> (bit & 63)) & 1 != 0
}
// ID_Start: 158,739 points; 789 records; 695 validated merged ranges.
// ID_Continue: 162,100 points; 1437 records; 814 validated merged ranges.

// 256 scalar slots per page; interleaved ID_Start and ID_Continue bits.
// 4352 one-byte indices + 132 unique 64-byte pages = 12,800 bytes.
#[rustfmt::skip]
const PAGE_INDEX: [u8; 4352] = [
    0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 1, 17, 18, 19, 1, 20, 21, 22, 23, 24, 25, 26, 27, 1, 28,
    29, 30, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 32, 33, 31, 31, 34, 35, 31, 31, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 36, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 1, 37, 1, 38, 39, 40, 41, 42, 43, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 44, 31, 31, 31, 31, 31, 31, 31, 31,
    31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 1, 45, 46, 1, 47, 48, 49,
    50, 51, 52, 53, 54, 55, 1, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80,
    1, 1, 1, 81, 82, 83, 84, 31, 31, 31, 31, 31, 31, 31, 31, 85, 1, 1, 1, 1, 86, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 87, 1, 1, 88, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31,
    31, 89, 31, 31, 31, 31, 31, 31, 1, 1, 90, 91, 31, 92, 93, 94, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 95, 96, 1, 1, 1, 97, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31,
    31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 98, 1, 99, 100, 31, 31, 31, 31, 31, 31, 31, 31, 31, 101, 31, 31, 31,
    31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 102, 31, 31, 103, 31, 104, 105, 31, 106, 107, 108, 109, 31, 31, 110, 31, 31, 31, 31, 111,
    112, 113, 114, 31, 115, 116, 117, 118, 119, 120, 31, 31, 31, 31, 121, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 102, 31, 31, 31, 31,
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 1, 1, 1, 122, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 123, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 124, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 125, 1, 1, 126, 31, 31, 31, 31, 31, 31, 31, 31, 31, 1, 1, 127, 31, 31, 31, 31, 31,
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 128, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 129, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31,
    31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31,
    31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31,
    31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31,
    31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31,
    31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 130, 31, 31, 31,
    31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31,
    31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31,
    31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31,
    31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31,
    31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31,
    31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31,
    31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31,
    31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31,
    31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31,
    31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31,
    31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31,
    31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31,
    31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31,
    31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31,
    31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31,
    31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31,
    31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31,
    31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31,
    31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31,
    31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31,
    31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31,
    31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31,
    31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31,
    31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31,
    31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31,
    31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31,
    31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31,
    31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31,
    31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31,
    31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31,
    31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31,
    31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31,
    31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31,
    31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31,
    31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31,
    31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31,
    31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31,
    31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31,
    31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31,
    31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31,
    31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31,
    31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31,
    31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31,
    31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31,
    31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31,
    31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31,
    31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31,
    31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31,
    31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31,
    31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31,
    31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31,
    31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31,
    31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31,
    31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31,
    31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31,
    31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31,
    31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31,
    31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31,
    31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31,
    31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31,
    31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31,
    31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31,
    31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31,
    31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31,
    31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31,
    31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31,
    31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31,
    31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31,
    31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31,
    31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31,
    31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31,
    31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31,
    31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31,
    31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31,
    31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31,
    31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31,
    31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31,
    31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31,
    31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31,
    31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31,
    31, 131, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31,
    31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31,
    31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31,
    31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31,
    31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31,
    31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31,
    31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31,
    31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31,
    31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31,
    31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31,
    31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31,
    31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31,
    31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31,
    31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31,
    31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31,
    31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31,
    31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31,
    31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31,
    31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31,
    31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31,
    31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31,
    31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31,
    31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31,
    31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31,
];

#[rustfmt::skip]
const IDENTIFIER_PAGES: [[u64; 8]; 132] = [
    [0x0000000000000000, 0x000aaaaa00000000, 0x803ffffffffffffc, 0x003ffffffffffffc, 0x0000000000000000, 0x00308c0000300000, 0xffff3fffffffffff, 0xffff3fffffffffff],
    [0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff],
    [0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0x0000000ffffff00f, 0x00000000330003ff],
    [0xaaaaaaaaaaaaaaaa, 0xaaaaaaaaaaaaaaaa, 0xaaaaaaaaaaaaaaaa, 0xcff0f3ffaaaaaaaa, 0xfffffffff33fb000, 0xffffffffffffffcf, 0xffffffffffffffff, 0xffffcfffffffffff],
    [0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xfffffffffff0aa8f, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff],
    [0xffffffffffffffff, 0xfffffffcffffffff, 0x000f3fffffffffff, 0xffffffffffffffff, 0xaaaaaaa803c3ffff, 0x8aaaaaaaaaaaaaaa, 0xffffffff000a8a28, 0x0000003fc03fffff],
    [0x002aaaaa00000000, 0xffffffffffffffff, 0xaaaaaaaaaabfffff, 0xfffffffef00aaaaa, 0xffffffffffffffff, 0xffffffffffffffff, 0x82aaacffffffffff, 0xc3faaaaafaa2beaa],
    [0xfffffffb00000000, 0xaaaaaaaaffffffff, 0xfffffffffc2aaaaa, 0xffffffffffffffff, 0xffffffffffffffff, 0x0000000eaaaaafff, 0xfffffffffffaaaaa, 0x08300faaaabfffff],
    [0xaabaafffffffffff, 0x000000000aababaa, 0x00abffffffffffff, 0xffffffff003fffff, 0xaaaa8000fffcffff, 0xffffffffffffffff, 0xaaaaaaaaaaafffff, 0xaaaaaaaaaaaaaa8a],
    [0xffffffffffffffaa, 0xaeafffffffffffff, 0xffffaaabaaaaaaaa, 0xfffffffcaaaaa0af, 0xffffffc3c3fffcab, 0xae0ff033fff3ffff, 0xcf0080003a8282aa, 0x2300000faaaaa0af],
    [0xffffffc3c03ffca8, 0xa20f3cf3fff3ffff, 0x33fc00080a82802a, 0x00000bfaaaaaa000, 0xffffffcfcffffca8, 0xae0ffcf3fff3ffff, 0x000000030a8a8aaa, 0xaaac0000aaaaa0af],
    [0xffffffc3c3fffca8, 0xae0ffcf3fff3ffff, 0xcf00aa800a8282aa, 0x0000000caaaaa0af, 0xf33c0ff3f03ffce0, 0xa00ffffff03f03c0, 0x000080030aa2a02a, 0x00000000aaaaa000],
    [0xfffffff3f3fffeaa, 0xae0ffffffff3ffff, 0x0f3f28000aa2a2aa, 0x00000000aaaaa0af, 0xfffffff3f3fffcab, 0xae0ffcfffff3ffff, 0x3f0028000aa2a2aa, 0x000000bcaaaaa0af],
    [0xfffffff3f3ffffaa, 0xaebfffffffffffff, 0xc000bf003aa2a2aa, 0xfff00000aaaaa0af, 0xfff03ffffffffca8, 0x0cffffcfffffffff, 0xaaaa22aa80203fff, 0x000000a0aaaaa000],
    [0xfffffffffffffffc, 0x002aaafbffffffff, 0x000aaaaa2aaabfff, 0x0000000000000000, 0xffffffffff3ff33c, 0x0eaaaafbffffccff, 0xff0aaaaa2aaa33ff, 0x0000000000000000],
    [0x000a000000000003, 0xa0088800000aaaaa, 0xfffffffffffcffff, 0xaaaaaaa803ffffff, 0xaaa8aaaaabffa2aa, 0x02aaaaaaaaaaaaaa, 0x0000000000002000, 0x0000000000000000],
    [0xffffffffffffffff, 0xeaaaaaaaaabfffff, 0xaffaafff000aaaaa, 0xfffffeabfaaabeae, 0x0aaaaaaabaaaaaaf, 0xffffffffffffffff, 0xffffffff0c00cfff, 0xff3fffffffffffff],
    [0xffffffffffffffff, 0xffffffffffffffff, 0x0ff33fff0ff3ffff, 0xffffffffffffffff, 0xffffffff0ff3ffff, 0x3fff0ff3ffffffff, 0xffff3fffffff0ff3, 0xffffffffffffffff],
    [0xffff0ff3ffffffff, 0xffffffffffffffff, 0xa83fffffffffffff, 0x0000000aaaa80000, 0x00000000ffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0x0fff0fffffffffff],
    [0xfffffffffffffffc, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff],
    [0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffc3ffffff, 0x003ffffffffffffc, 0xffffffffffffffff, 0xffffffffffffffff, 0x0003fffff03fffff],
    [0xc0000aafffffffff, 0x000002afffffffff, 0x000000afffffffff, 0x000000a3f3ffffff, 0xffffffffffffffff, 0xaaaaaaffffffffff, 0x0b00c0aaaaaaaaaa, 0x00000000000aaaaa],
    [0x000aaaaa8a800000, 0xffffffffffffffff, 0xffffffffffffffff, 0x0003ffffffffffff, 0xffffffffffffffff, 0xffffffff003bffff, 0xffffffffffffffff, 0x00000fffffffffff],
    [0x3fffffffffffffff, 0x00aaaaaa00aaaaaa, 0xffffffffaaaaa000, 0x000003ff0fffffff, 0xffffffffffffffff, 0xffffffff00ffffff, 0x002aaaaa000fffff, 0x0000000000000000],
    [0x00aabfffffffffff, 0xffffffffffffffff, 0x2aaaabffffffffff, 0x82aaaaaaaaaaaaaa, 0x000aaaaa000aaaaa, 0x8aaaaaaa0000c000, 0xaaaaaaaaaaaaaaaa, 0x00000002aaaaaaaa],
    [0xfffffffffffffeaa, 0xaaaaaaffffffffff, 0x000aaaaa03fffeaa, 0x000000aaaa800000, 0xffffffffffffffea, 0xfffaaaaafaaaaaab, 0xffffffffffffffff, 0x000000aaaaaaafff],
    [0xffffffffffffffff, 0x0000aaaaaaaaaaff, 0xfffaaaaafc0aaaaa, 0x0fffffffffffffff, 0xffffffff003fffff, 0xfc3fffffffffffff, 0xaaaaaa2a00000000, 0x003abefffbfeaaaa],
    [0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xaaaaaaaaaaaaaaaa, 0xaaaaaaaaaaaaaaaa],
    [0x0fff0fffffffffff, 0xffffffffffffffff, 0xccccffff0fff0fff, 0x0fffffffffffffff, 0xffffffffffffffff, 0x33fff3ffffffffff, 0x00fff0ff03fff3f0, 0x03fff3f003ffffff],
    [0x000000000a000000, 0x8000000000000000, 0x0000020000000002, 0xc000000c00000000, 0xffffffffc0000000, 0x0000000000000000, 0x02aaaaaa00000000, 0x00000002aaaaa808],
    [0x0fff0cfffff0c030, 0xff0ffffffff33300, 0x00000000300ffc00, 0xffffffffffffffff, 0x000000000003ffff, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000],
    [0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000],
    [0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0x000000fabfc003ff],
    [0xffffffffffffffff, 0xffffffff0c00cfff, 0xffffffffffffffff, 0x80000000c000ffff, 0x00003fffffffffff, 0x3fff3fff3fff3fff, 0x3fff3fff3fff3fff, 0xaaaaaaaaaaaaaaaa],
    [0x000000000000fc00, 0x03ff0ffcaaaffffc, 0xfffffffffffffffc, 0xffffffffffffffff, 0xffe83fffffffffff, 0xfffffffffffffffc, 0xffffffffffffffff, 0xffbfffffffffffff],
    [0xfffffffffffffc00, 0xfffffffcffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0x000000003fffffff, 0xffffffffffffffff, 0x0000000000000000, 0xffffffff00000000],
    [0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0x0000000000000000, 0x0000000000000000],
    [0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0x0000000003ffffff, 0x0000000000000000, 0xffffffff00000000, 0x0fffffffffffffff],
    [0xffffffff03ffffff, 0x0000000000faaaaa, 0xffffffffffffffff, 0xcaaaaa00bfffffff, 0xafffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0x0000000affffffff],
    [0xffffc00000000000, 0xfffffffffffffff0, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffc3ffff, 0xffffffffffffffff, 0x0fffffffffffffff, 0xfffffffc00000030],
    [0xffffffffffbfefef, 0x000000000200aabf, 0xffffffffffffffff, 0x000000ffffffffff, 0xfffffffffffffffa, 0xaaaaaaffffffffff, 0x000aaaaa00000aaa, 0xbcc0fffaaaaaaaaa],
    [0xfffffffffffaaaaa, 0xffffffff0aaaafff, 0x000000aaaaaabfff, 0x03ffffffffffffff, 0xffffffffffffffaa, 0xaaaaaabfffffffff, 0x000aaaaac0000002, 0x3ffaaaaafffffbff],
    [0xffffffffffffffff, 0x00002aaaaaabffff, 0x000aaaaa0affffbf, 0xfab03fffffffffff, 0xffffffffffffffff, 0xaffebeaeffffffff, 0x0fc000000000003b, 0x00002bf0aabfffff],
    [0x00003ffc3ffc3ffc, 0xffffffff3fff3fff, 0xff3fffffffffffff, 0xffffffff0f0fffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0x000aaaaa0a2aaabf],
    [0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffff000000ff, 0xffffffffffc03fff, 0x00ffffffffffffff],
    [0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffff0fffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0x000fffffffffffff, 0x0000000000000000],
    [0xec00ffc000003fff, 0x33ff3ffffff3ffff, 0xfffffffffffff3cf, 0xffffffffffffffff, 0xffffffffffffffff, 0x0000000fffffffff, 0xffffffc000000000, 0xffffffffffffffff],
    [0xffffffffffffffff, 0x0fffffffffffffff, 0xffffffff00000000, 0xffffffffffffffff, 0xfffffff0ffffffff, 0xffffffffffffffff, 0x000000000000ffff, 0x00ffffff00000000],
    [0x00000000aaaaaaaa, 0x00000280aaaaaaaa, 0x00000000a8000000, 0xfffff3ff00000000, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0x03ffffffffffffff],
    [0x000aaaaa00000000, 0x803ffffffffffffc, 0x003ffffffffffffc, 0xfffffffffffff800, 0xffffffffffffffff, 0x3fffffffffffffff, 0x03f0fff0fff0fff0, 0x0000000000000000],
    [0xfffffffffcffffff, 0xcf3fffffffff3fff, 0x0fffffff0fffffff, 0x0000000000000000, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0x003fffffffffffff],
    [0x0000000000000000, 0x0000000000000000, 0xffffffffffffffff, 0x000003ffffffffff, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0800000000000000],
    [0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x03ffffffffffffff, 0xffffffffffffffff, 0x00000003ffffffff, 0x0000000000000002],
    [0xffffffffffffffff, 0xfffffffffc000000, 0xffffffff003fffff, 0x002aafffffffffff, 0x0fffffffffffffff, 0xffffffffffffffff, 0x00000ffcffff00ff, 0x0000000000000000],
    [0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0x0fffffffffffffff, 0xffffffff000aaaaa, 0xffff00ffffffffff, 0x00ffffffffffffff],
    [0xffffffffffffffff, 0xffffffff0000ffff, 0xffffffffffffffff, 0xff3fffff000000ff, 0xffffcf3fff3fffff, 0x03cfffcfffffffcf, 0xffffffffffffffff, 0x000000ffffffffff],
    [0xffffffffffffffff, 0x00003fffffffffff, 0x00000fffffffffff, 0x000000000000ffff, 0xffffffffffffcfff, 0xfffffff3ffffffff, 0x0000000000000000, 0x0000000000000000],
    [0xfffffffffff30fff, 0xc303cfffffffffff, 0x00000fffffffffff, 0x00003fffffffffff, 0x3fffffffffffffff, 0x0000000000000000, 0x0000000000000000, 0x00000f3fffffffff],
    [0x00000fffffffffff, 0x000fffffffffffff, 0x000fffffffffffff, 0x0000000000000000, 0xffffffffffffffff, 0xf000ffffffffffff, 0x0000000000000000, 0x0000000000000000],
    [0xfffcfcffaa0028ab, 0x802a0fffffffffff, 0x0000000000000000, 0x03ffffffffffffff, 0x03ffffffffffffff, 0x0000000000000000, 0xfffffffffffcffff, 0x0000000000002bff],
    [0xffffffffffffffff, 0x00000fffffffffff, 0x00000fffffffffff, 0x0000003fffffffff, 0x0000000fffffffff, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000],
    [0xffffffffffffffff, 0xffffffffffffffff, 0x000000000003ffff, 0x0000000000000000, 0xffffffffffffffff, 0x0000003fffffffff, 0xffffffffffffffff, 0x0000003fffffffff],
    [0xffffffffffffffff, 0x000aaaaa0000aaff, 0xfffffffffffaaaaa, 0xffffffffcaa80fff, 0x0000000000000fff, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000],
    [0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0xffffffffffffffff, 0x0000000f028fffff, 0xfffc0000aa80fff0, 0xaaaaaaaa3fffffff],
    [0x03ffffffffffffff, 0xffffffff0000c000, 0x00000002aaaaafff, 0xffffffff00000000, 0x0000000000000aaf, 0xffffffff00000000, 0x00000000000003ff, 0x00003fffffffffff],
    [0xffffffffffffffea, 0xaaaaffffffffffff, 0x0000000000002aaa, 0x80000ebeaaaaa000, 0xffffffffffffffea, 0x002aaaaaffffffff, 0xffffffff00000020, 0x000aaaaa0003ffff],
    [0xffffffffffffffea, 0xaaaaa2aaaaaabfff, 0xffffffff0000eb00, 0x000030bfffffffff, 0xffffffffffffffea, 0xaaaaaabfffffffff, 0x033aaaaaa2a803fe, 0x0000000000000000],
    [0xffffffcfffffffff, 0xe000aaaaaaffffff, 0x000000000000000b, 0x0000000000000000, 0xcfffffffcff33fff, 0xffffffff0003ffff, 0xbfffffffffffffff, 0x000aaaaa002aaaaa],
    [0xffffffc3c3fffcaa, 0xae8ffcf3fff3ffff, 0xfc0080030a8282aa, 0x000002aa02aaa0af, 0xffffffff30cfffff, 0xaaaacfffffffffff, 0x000000eeaa2a8822, 0x0000000000000028],
    [0xffffffffffffffff, 0xaaaaabffffffffff, 0xe00aaaaa003feaaa, 0x000000000000000f, 0xffffffffffffffff, 0xaaaaaaaaffffffff, 0x000aaaaa0000cfaa, 0x0000000000000000],
    [0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0xffffffffffffffff, 0xaaaa0aaabfffffff, 0x0aff000000000002, 0x0000000000000000],
    [0xffffffffffffffff, 0xaaaaaaaaffffffff, 0x000aaaaa00000302, 0x0000000000000000, 0xffffffffffffffff, 0x0003aaaaaabfffff, 0xaaaaaaaa000aaaaa, 0x00000000000000aa],
    [0xa83fffffffffffff, 0x000aaaaa00aaaaaa, 0x0000000000003fff, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000],
    [0xffffffffffffffff, 0x002aaaaaaaffffff, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0xffffffffffffffff, 0xffffffffffffffff, 0xc0000000000aaaaa],
    [0xffff3cffff0c3fff, 0xea828aaaffffffff, 0x000aaaaa000000ae, 0x0000000000000000, 0x0000000000000000, 0xfffffffffff0ffff, 0xaaa0aaabffffffff, 0x00000000000002ce],
    [0xffffffffffeaaaab, 0x2abaaabfffffffff, 0xffaaaaab00008000, 0xffffffffffffffff, 0x0c0aaaaaaaafffff, 0xffffffff00000000, 0xffffffffffffffff, 0x0003ffffffffffff],
    [0x0000000000300000, 0x0000000000000000, 0x0000000000000000, 0x000000000000aaaa, 0x0000000000000000, 0x0000000000000000, 0xffffffffffffffff, 0x000aaaaa00000003],
    [0xfffffffffff3ffff, 0xaaaa2aaabfffffff, 0x000aaaaa00000003, 0xfffffff000000000, 0xaaaaaaa0ffffffff, 0x00002aaaaaa8aaaa, 0x0000000000000000, 0x0000000000000000],
    [0xffffffffffcf3fff, 0x8a202aabffffffff, 0x000aaaaa0000baaa, 0xfffffffffff3cfff, 0x0003aa8a2aafffff, 0xffffffff000aaaaa, 0x00ffffffffffffff, 0x0000000e000aaaaa],
    [0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x00002abfffffffff],
    [0xfffffff3ffffffba, 0xa02aaaffffffffff, 0x002aaaaa0000002a, 0x0000000000000000, 0x0000000000000000, 0x0000000300000000, 0x0000000000000000, 0x0000000000000000],
    [0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0x000fffffffffffff, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000],
    [0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xfffffc00ffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff],
    [0xffffffffffffffff, 0xffffffffffffffff, 0xffffffff000000ff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff],
    [0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0x0000000000003fff, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000],
    [0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0xffffffff00000000, 0xffffffffffffffff, 0xffffffffffffffff, 0x00000003ffffffff],
    [0xffffffffffffffff, 0x00000000ffffffff, 0x00000aaaaaaabffe, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff],
    [0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0x003fffffffffffff],
    [0xffffffffffffffff, 0xffffffffffffffff, 0x0000000000003fff, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000],
    [0xafffffffffffffff, 0x000aaaaaaaaaaaaa, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000],
    [0xffffffffffffffff, 0x0003ffffffffffff, 0x3fffffffffffffff, 0xffffffff000aaaaa, 0xffffffffffffffff, 0x3fffffffffffffff, 0xffffffff000aaaaa, 0x000002aa0fffffff],
    [0xffffffffffffffff, 0x00002aaaffffffff, 0x000aaaaa000000ff, 0xfc00ffffffffffc0, 0x00000000ffffffff, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000],
    [0x0000000000000000, 0x0000000000000000, 0xffffffffffffffff, 0x000aaaaa03ffffff, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000],
    [0x0000000000000000, 0x0000000000000000, 0xffffffffffffffff, 0xffffffffffffffff, 0x0000000000000000, 0xffc3ffffffffffff, 0x000000ffffffffff, 0x0000000000000000],
    [0xffffffffffffffff, 0xffffffffffffffff, 0xaaaaaaab803fffff, 0xaaaaaaaaaaaaaaaa, 0xffffffea8000aaaa, 0x0000000000000000, 0x0000000000000000, 0x00003ffa000002cf],
    [0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0x003fffffffffffff, 0xc000000000000000],
    [0xffffffffffffffff, 0x0000000000000003, 0x0000000000000000, 0x0000000000000000, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0x0000003fffffffff],
    [0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0x0000000fffffffff, 0xffffffffffffffff, 0x0000003fffffffff, 0x0000000000000000],
    [0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x3cfffcff00000000],
    [0xffffffffffffffff, 0x000000300003ffff, 0x00000c3f00000000, 0xffffffff0003ff00, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff],
    [0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0x00ffffffffffffff],
    [0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0x03ffffff003fffff, 0x280fffff0003ffff, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000],
    [0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x000aaaaa00000000],
    [0xaaaaaaaaaaaaaaaa, 0xaaaaaaaa0aaaaaaa, 0x0000000000002aaa, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000],
    [0x0000000000000000, 0x0000000000028000, 0x0000000000000000, 0xaa80002aa80aa800, 0x0000000000aaa82a, 0x000000000aa00000, 0x0000000000000000, 0x0000000000000000],
    [0x0000000000000000, 0x0000000000000000, 0x8280002a000002a0, 0x0000000000000000, 0x000000000000000a, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000],
    [0xffffffffffffffff, 0xffffffffffffffff, 0xfffff3ffffffffff, 0xffffffffffffffff, 0xf3ffffffffffffff, 0xfccffffff3fc3c30, 0xfffffffffffffcff, 0xffffffffffffffff],
    [0xf3fff3fffc3fcfff, 0x3fcfffffffffffff, 0xfffffff3fff033ff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff],
    [0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffff3fff, 0xff3ffffffffffff3, 0xff3fffffffffffff],
    [0xfffff3ffffffffff, 0xfffff3ffffffffff, 0xffffffff3fffffff, 0xffffffff3fffffff, 0xfffffffffff3ffff, 0xfffffffffff3ffff, 0xaaaaaaaaa0ffff3f, 0xaaaaaaaaaaaaaaaa],
    [0xaaaaaaaaaaaaaaaa, 0xaa802aaaaaaaaaaa, 0xaaaaaaaaaaaaaaaa, 0x0000080002aaaaaa, 0xaa80000000000200, 0x00000000aaaaaaa8, 0x0000000000000000, 0x0000000000000000],
    [0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0x00003fff0000000f, 0x0000000000000000, 0xfffffffffc000000, 0xffffffffffffffff],
    [0xaa82aaaaaaaa2aaa, 0xffffffff002aa28a, 0xffffffffffffffff, 0x000000000fffffff, 0x0000000080000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000],
    [0xffffffffffffffff, 0x0fffeaaa03ffffff, 0x00000000300aaaaa, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000],
    [0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0xffffffff00000000, 0x000000002fffffff, 0xffffffffffffffff, 0x000aaaaaaaffffff],
    [0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0xffffffff00000000, 0x000aaaaaaaffffff],
    [0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0xffffffff00000000, 0x002aaaabafffffff],
    [0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x3fffffffffffffff, 0xf0000bffafffefbf],
    [0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x3fffffff3cff3fff],
    [0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0x00002aaa000003ff, 0x0000000000000000],
    [0xffffffffffffffff, 0xffffffffffffffff, 0x000aaaaa00eaaaff, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000],
    [0xfffffffffffffcff, 0x00ccff3ffffcc33c, 0xccccc33cfcccc030, 0x33fcff3fff3fc33c, 0x00ffffffffcfffff, 0x00ffffffffcffcfc, 0x0000000000000000, 0x0000000000000000],
    [0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0x0000000000000000],
    [0x3fffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff],
    [0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffff0fffffff, 0xffffffffffffffff, 0xffffffffffffffff],
    [0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffff00000003],
    [0xffffffffffffffff, 0xffffffffffffffff, 0x0fffffffffffffff, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000],
    [0x0fffffffffffffff, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000],
    [0xffffffffffffffff, 0xffffffffffffffff, 0xffffffff003fffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff],
    [0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0x000fffffffffffff, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000],
    [0xffffffffffffffff, 0xffffffffffffffff, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000],
    [0xaaaaaaaaaaaaaaaa, 0xaaaaaaaaaaaaaaaa, 0xaaaaaaaaaaaaaaaa, 0xaaaaaaaaaaaaaaaa, 0xaaaaaaaaaaaaaaaa, 0xaaaaaaaaaaaaaaaa, 0xaaaaaaaaaaaaaaaa, 0x00000000aaaaaaaa],
];

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn ecmascript_additions_and_id_not_xid_examples() {
        assert_eq!(IDENTIFIER_LOOKUP_WORK, 2);
        for value in ['$', '_', 'A', 'z', '\u{37a}', '\u{2118}', '\u{10400}'] {
            assert!(is_identifier_start(value), "{value:?}");
            assert!(is_identifier_part(value), "{value:?}");
        }
        for value in [
            '0', '\u{300}', '\u{b7}', '\u{203f}', '\u{660}', '\u{200c}', '\u{200d}',
        ] {
            assert!(!is_identifier_start(value), "{value:?}");
            assert!(is_identifier_part(value), "{value:?}");
        }
        for value in ['\0', '\u{b2}', '\u{feff}', '\u{1f600}', '\u{10ffff}'] {
            assert!(!is_identifier_start(value), "{value:?}");
            assert!(!is_identifier_part(value), "{value:?}");
        }
    }

    #[test]
    fn every_scalar_matches_independently_read_pinned_property_records() {
        // Independent from the Python parser/generator: expand the original
        // property records directly into bitmaps, then exercise the real API.
        let data = include_str!("../tests/upstream/unicode/18.0.0/DerivedCoreProperties.txt");
        let mut start = vec![false; 0x110000];
        let mut part = vec![false; 0x110000];
        for line in data.lines() {
            let record = line.split('#').next().unwrap().trim();
            let mut fields = record.split(';').map(str::trim);
            let Some(range) = fields.next() else { continue };
            let bitmap = match fields.next() {
                Some("ID_Start") => &mut start,
                Some("ID_Continue") => &mut part,
                _ => continue,
            };
            let mut ends = range.split("..");
            let first = u32::from_str_radix(ends.next().unwrap(), 16).unwrap();
            let last = ends
                .next()
                .map_or(first, |end| u32::from_str_radix(end, 16).unwrap());
            for value in first..=last {
                assert!(char::from_u32(value).is_some());
                assert!(!bitmap[value as usize]);
                bitmap[value as usize] = true;
            }
        }
        assert_eq!(start.iter().filter(|&&value| value).count(), 158739);
        assert_eq!(part.iter().filter(|&&value| value).count(), 162100);
        for raw in 0..=0x10ffff {
            let Some(value) = char::from_u32(raw) else {
                continue;
            };
            assert_eq!(
                is_identifier_start(value),
                start[raw as usize] || matches!(value, '$' | '_'),
                "start U+{raw:04X}"
            );
            assert_eq!(
                is_identifier_part(value),
                part[raw as usize] || matches!(value, '$' | '\u{200c}' | '\u{200d}'),
                "part U+{raw:04X}"
            );
        }
    }
}
